name: Build, Analyze, and Deploy Node.js App

on:
  push:
    branches:
      - main

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  analyze:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Analyze code quality with SonarQube
        uses: sonarsource/sonarcloud-github-action@master
        with:
          token: ${{ env.SONAR_TOKEN }}
          hostUrl: ${{ env.SONAR_HOST_URL }}

  build-docker-image:
    needs: analyze
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t my-dockerhub-username/my-node-js-app:latest .

      - name: Push Docker image to Dockerhub
        run: docker push my-dockerhub-username/my-node-js-app:latest
